# Offense count: 5
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle.
# SupportedStyles: always, always_true, never
Style/FrozenStringLiteralComment:
  Exclude:
    - 'app/models/category.rb'
    - 'app/models/product.rb'
    - 'app/models/product_category.rb'
    - 'app/models/shop.rb'
    - 'app/models/shop_product.rb'
